---
- name: Configure important user consistently
  hosts: localhost
  become: true
  become_method: su
  tasks:
    - name: newbie exists with UID 4000
      user:
        name: newbie
        uid: 4000
        state: present
