---
- name: Manage users
  hosts: localhost
  become: true

  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: johnd
        comment: John Doe
        uid: 1040
        group: admin

    - name: Ensure 'admin' group exists
      ansible.builtin.group:
        name: admin
        state: present

    - name: Create a user 'johnd' with a home directory
      ansible.builtin.user:
        name: johnd
        create_home: yes

    - name: Ensure 'admins' and 'developers' groups exist
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - admins
        - developers

    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      ansible.builtin.user:
        name: james
        shell: /bin/bash
        groups: admins,developers
        append: yes

    - name: Remove the user 'johnd'
      ansible.builtin.user:
        name: johnd
        state: absent
        remove: yes

    - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      ansible.builtin.user:
        name: jsmith
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Ensure 'developers' group exists for the consultant
      ansible.builtin.group:
        name: developers
        state: present

    - name: Add a consultant whose account you want to expire
      ansible.builtin.user:
        name: james18
        shell: /bin/zsh
        groups: developers
        expires: 1422403387

    - name: Modify user 'james18', remove expiry time (Ansible 2.6+)
      ansible.builtin.user:
        name: james18
        expires: -1

    - name: Set maximum expiration date for password of user 'ram19'
      ansible.builtin.user:
        name: ram19
        password_expire_max: 10

    - name: Set minimum expiration date for password of user 'pushkar15'
      ansible.builtin.user:
        name: pushkar15
        password_expire_min: 5

    - name: Set number of warning days for password expiration of user 'jane157'
      ansible.builtin.user:
        name: jane157
        password_expire_warn: 30
